from tkinter import *

frame_root = Tk()
frame_root.geometry("655x333")
frame_root.title("Frames")
f1 = Frame(frame_root, bg = "grey" , borderwidth =6, relief = SUNKEN)
f1.pack(side = LEFT, fill=Y)
f2 = Frame(frame_root, borderwidth =8, bg="blue", relief=SUNKEN)
f2.pack(side=TOP, fill=X)
f3 = Frame(frame_root, borderwidth = 8, bg="red", relief=GROOVE)
f3.pack(side=BOTTOM, fill=X)
f4= Frame(frame_root, borderwidth =9, bg="grey", relief=SUNKEN)
f4.pack(side=RIGHT, fill=Y)
l1 = Label(f1, text = "project tkinter")
l1.pack(pady = 142)
l2 = Label(f2, text = "Welcome to subline text", font= "Helvetica 16 bold", fg="red", padx = 13)
l2.pack()
l3 = Label(f3, text="For any queries please dm")
l3.pack()
l4 = Label(f4, text= "Online E Voting System")
l4.pack()
frame_root.mainloop()